---
# Configure sudo tasks

- block:
    - name: Delete absent sudoers.d files
      file:
        path: "{{ sudo_sudoer_d_item.path }}"
        state: absent
      when: sudo_sudoer_d_item.state | default("present") == "absent"
      loop: "{{ sudo_sudoers_d_to_manage }}"
      loop_control:
        loop_var: sudo_sudoer_d_item
        label: "{{ sudo_sudoer_d_item.path }}"

    - name: Search /etc/sudoers.d files that exists
      find:
        paths: "{{ sudo_sudoers_d_path }}/"
        patterns: "*"
      register: search_sudoers_d_result

    - name: Delete unmanaged sudoers.d files
      file:
        path: "{{ sudo_sudoer_d_item }}"
        state: absent
      when: sudo_delete_unmanaged
      loop: >-
        {{ search_sudoers_d_result.files
           | default([])
           | map(attribute="path")
           | reject("in", sudo_sudoers_d_to_manage
                          | map(attribute="path")
                          | list)
           | list }}
      loop_control:
        loop_var: sudo_sudoer_d_item

    - name: Setup sudoers.d files
      template:
        backup: no
        src: sudoers.d.j2
        dest: "{{ sudo_sudoer_d_item.path }}"
        mode: 0440
        owner: root
        group: root
      register: sudo_setup_sudoers_d_result
      when: sudo_sudoer_d_item.state | default("present") == "present"
      loop: "{{ sudo_sudoers_d_to_manage }}"
      loop_control:
        loop_var: sudo_sudoer_d_item
        label: "{{ sudo_sudoer_d_item.path }}"

    - name: Setup /etc/sudoers config file
      when:
        - sudo_sudoers is not none
        - sudo_sudoers | default("") | length > 0
      template:
        backup: no
        src: sudoers.j2
        dest: /etc/sudoers
        mode: 0440
        owner: root
        group: root
  tags:
    - role::sudo
    - role::sudo::configure
