---
# Configure sudo tasks

- block:
    - name: Setup sudoers.d files
      template:
        backup: no
        src: sudoers.d.j2
        dest: "{{ sudo_sudoers_d_path }}/{{ sudo_sudoers_file_name }}"
        mode: 0440
        owner: root
        group: root
      register: sudo_setup_sudoers_d_result
      when: sudo_sudoer_d_item.value.state | default("present") == "present"
      loop: "{{ sudo_sudoers_d_to_manage | dict2items }}"
      loop_control:
        loop_var: sudo_sudoer_d_item
        label: "{{ sudo_sudoers_file_name }}"

    - name: Delete absent sudoers.d files
      file:
        path: "{{ sudo_sudoers_d_path }}/{{ sudo_sudoers_file_name }}"
        state: absent
      when: sudo_sudoer_d_item.value.state | default("present") == "absent"
      loop: "{{ sudo_sudoers_d_to_manage | dict2items }}"
      loop_control:
        loop_var: sudo_sudoer_d_item
        label: "{{ sudo_sudoers_file_name }}"

    - name: Search /etc/sudoers.d files that exists
      find:
        paths: "{{ sudo_sudoers_d_path }}/"
        patterns: "*"
      register: search_sudoers_d_result

    - name: Delete unmanaged sudoers.d files
      file:
        path: "{{ sudo_sudoers_d_path }}/{{ sudo_sudoer_d_item }}"
        state: absent
      when: sudo_delete_unmanaged
      loop: >-
        {{ search_sudoers_d_result.files
           | default([])
           | map(attribute="path")
           | map("basename")
           | reject("in", sudo_sudoers_d_filenames)
           | list }}
      loop_control:
        loop_var: sudo_sudoer_d_item
      vars:
        sudo_sudoers_d_filenames: >-
          {{ sudo_setup_sudoers_d_result.results
             | selectattr("invocation.module_args.dest", "defined")
             | map(attribute="invocation.module_args.dest")
             | map("basename")
             | list }}

    - name: Setup /etc/sudoers config file
      when:
        - sudo_sudoers is not none
        - sudo_sudoers | default("") | length > 0
      template:
        backup: no
        src: sudoers.j2
        dest: /etc/sudoers
        mode: 0440
        owner: root
        group: root
  vars:
    sudo_sudoers_file_name: >-
      {{ "%02d" | format(sudo_sudoer_d_item.value.priority)
         + "-"
         + sudo_sudoer_d_item.key }}

    sudo_sudoers_d_to_manage: >-
      {{ sudo_sudoers_d
         | combine((sudo_load_sudoers_d_from_hostvars)
            | ternary(sudo_sudoers_d_hostvars | default({}) | flatten, {})) }}
  tags:
    - role::sudo
    - role::sudo::configure
