---
# Configure sudo tasks

- block:
    - name: Create sudoers.d files
      template:
        backup: no
        src: sudoers.d.j2
        dest: "{{ sudo_sudoers_d_path }}/{{ sudo_sudoer_d_item.key }}"
        mode: 0440
        owner: root
        group: root
      loop: "{{ sudo_sudoers_d_to_manage | dict2items }}"
      loop_control:
        loop_var: sudo_sudoer_d_item
        label: "{{ sudo_sudoer_d_item.key }}"

    - name: Search /etc/sudoers.d files that exists
      find:
        paths: "{{ sudo_sudoers_d_path }}/"
        patterns: "*"
      register: search_sudoers_d_result

    - name: Delete unmanaged sudoers.d files
      file:
        path: "{{ sudo_sudoers_d_path }}/{{ sudo_sudoer_d_item }}"
        state: absent
      when: sudo_delete_unamanaged
      loop: >-
        {{ search_sudoers_d_result.files
           | default([])
           | map(attribute="path")
           | map("basename")
           | reject("in", sudo_sudoers_d_to_manage.keys() | list)
           | list }}
      loop_control:
        loop_var: sudo_sudoer_d_item

    - name: Setup /etc/sudoers config file
      when: sudo_sudoers | default("") | length > 0
      template:
        backup: no
        src: sudoers.j2
        dest: /etc/sudoers
        mode: 0440
        owner: root
        group: root
  vars:
    sudo_sudoers_d_to_manage: >-
      {{ sudo_sudoers_d
         | combine((sudo_load_sudoers_d_from_hostvars)
            | ternary(sudo_sudoers_d_hostvars | default({}) | flatten, {})) }}
  tags:
    - role::sudo
    - role::sudo::configure
