---
# Sudo install tasks

- name: create sudoers.d directory
  file:
    path: "{{ sudo_sudoers_d_path }}"
    owner: root
    group: root
    mode: 0755
  tags:
    - role::sudo
    - role::sudo::install
