---
# Main sudo tasks

- name: install sudo
  import_tasks: install.yml
  tags:
    - role::sudo
    - role::sudo::install

- name: configure sudo
  import_tasks: configure.yml
  tags:
    - role::sudo
    - role::sudo::configure
