---
# Main sudo tasks

- name: install sudo
  include: install.yml
  tags:
    - role::sudo
    - role::sudo::install

- name: configure sudo
  include: configure.yml
  tags:
    - role::sudo
    - role::sudo::configure
