---
# Setup sudo

- block:
  - name: install sudo package
    package:
      name: sudo
      state: latest

  - name: create sudoers.d directory
    file:
      path: "{{ sudo_sudoers_d_path }}"
      owner: root
      group: root
      mode: 0755

  - name: setup /etc/sudoers config file
    template:
      backup: no
      src: sudoers.j2
      dest: /etc/sudoers
      mode: 0440
      owner: root
      group: root

  - name: search /etc/sudoers.d files that exists
    find:
      paths: "{{ sudo_sudoers_d_path }}/"
      patterns: "*"
    register: search_sudoers_d_result

  - name: create sudoers.d files
    template:
      backup: no
      src: sudoers.d.j2
      dest: "{{ sudo_sudoers_d_path }}/{{ sudoer_d }}"
      mode: 0440
      owner: root
      group: root
    with_items: "{{ sudo.sudoers_d }}"
    loop_control:
      loop_var: sudoer_d

  - name: delete unnecessary sudoers.d files
    file: path={{ item.path }} state=absent
    when: "'{{ item.path | basename }}' not in sudo.sudoers_d"
    with_items: "{{ search_sudoers_d_result.files | default([]) }}"
    loop_control:
      label: "{{ item.path }}"

  tags:
    - security
    - sudo
