---

- import_playbook: ../resources/prepare_centos_6.yml

- name: Prepare
  hosts: molecule_hosts
  gather_facts: no
  tasks:
    - name: Create /etc/sudoers.d/unmanaged
      copy:
        content: ""
        dest: /etc/sudoers.d/unmanaged
        force: no
        mode: 0755
