---

- name: Verify
  hosts: molecule_hosts
  gather_facts: no
  tasks:
    - name: Check /etc/sudoers.d/05-unmanaged file
      stat:
        path: /etc/sudoers.d/05-unmanaged
      register: check_sudoers_d_unamanaged_result

    - name: Check sudoers.d content
      assert:
        that: check_sudoers_d_unamanaged_result.stat.exists
